### ISSUE TITLE
 Обновление Number в State

### ISSUE THREAD

**Issue by gHashTag** [RealPeha/telegraf-better-stage#1]
Как мне плюсовать счет в стейте с прошлым состоянием?

Так не работает

```javascript
const state = ctx.scene.state

ctx.scene.next({ score: state.score + 1 })

```

**Comment by RealPeha** [comment]
@gHashTag а что конкретно не работает, какую ошибку получаешь (есть ли вообще ошибка?) ? Установил ли ты начальное значение для score в стейт? Можешь посмотреть пример тут https://github.com/RealPeha/telegraf-better-stage/blob/master/examples/reg.js, возможно ты что-то упустил

**Comment by gHashTag** [comment]
Надо было +=
